-- Create tables for editable Industries and Services page content.
-- Run this file in Supabase SQL Editor.

create table if not exists public.services_page_content (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    sort_order integer not null default 0,
    badge text not null default '',
    title text not null,
    description text not null default '',
    details text not null default '',
    icon text not null default 'bi-gear',
    image_url text not null default '',
    is_teal boolean not null default false,
    is_reverse boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.industries_page_content (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    sort_order integer not null default 0,
    title text not null,
    summary text not null default '',
    details text not null default '',
    products_list text not null default '',
    image_url text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create or replace function public.andison_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists trg_services_page_content_updated_at on public.services_page_content;
create trigger trg_services_page_content_updated_at
before update on public.services_page_content
for each row execute procedure public.andison_touch_updated_at();

drop trigger if exists trg_industries_page_content_updated_at on public.industries_page_content;
create trigger trg_industries_page_content_updated_at
before update on public.industries_page_content
for each row execute procedure public.andison_touch_updated_at();

-- Optional seed rows so pages have content even before admin updates.
insert into public.services_page_content
(slug, sort_order, badge, title, description, details, icon, image_url, is_teal, is_reverse)
values
('consultation', 0, 'Expert Assistance', 'Technical Consultation', 'Expert guidance from our team of experienced industrial specialists. We provide comprehensive consultation on equipment selection, process optimization, and technical specifications to ensure you have the solid support and processes for your application.', 'Our consultation services include process optimization, equipment selection assistance, facility design and compliance audit support customized to support successful project implementation.', 'bi-gear', '', false, false),
('training', 1, 'Skill Development', 'Training Programs', 'Comprehensive training programs designed to enhance your team''s capabilities with advanced welding equipment and safety protocols. Our certified instructors provide hands-on training covering operator qualification, preventive procedures, and technical troubleshooting.', 'Training includes onsite training sessions, certification programs, hands and angle verification procedures, and comprehensive documentation to ensure technician competency and adherence to safety standards.', 'bi-book', '', true, true),
('maintenance', 2, 'Full Performance', 'Equipment Maintenance', 'Preventive maintenance and repair service to keep equipment operating at peak performance, maximize uptime and equipment lifespan. Our field service team ensures all critical equipment is properly maintained and emergency repairs are addressed immediately.', 'We maintain extensive preventive care upon the full inspection maintenance contract schedules such repairs, quick emergency support and emergency repairs. Also maintain complete spare parts inventory to minimize downtime and extend equipment lifespan.', 'bi-tools', '', false, false),
('support', 3, 'Ongoing Support', 'After-Sales Support', 'Dedicated support team to assist with troubleshooting, spare part procurement and application-specific guidance. We provide prompt response to ensure minimal disruption to your operations.', 'Our after-sales support includes company standardization technical documentation, software updates for remote systems and dispatch our integrated specialized team for comprehensive technical support and immediate availability.', 'bi-headset', '', true, true)
on conflict (slug) do update set
    sort_order = excluded.sort_order,
    badge = excluded.badge,
    title = excluded.title,
    description = excluded.description,
    details = excluded.details,
    icon = excluded.icon,
    image_url = excluded.image_url,
    is_teal = excluded.is_teal,
    is_reverse = excluded.is_reverse;

insert into public.industries_page_content
(slug, sort_order, title, summary, details, products_list, image_url)
values
('motor-vehicle', 0, 'Motor Vehicle Industry', 'This industry manufactures automobiles, motorcycles, buses, and truck vans. They have a growing presence in the Philippine market, especially with the high market for motorcycles. We offer a wide assortment of welding equipment and consumables necessary to produce world-class products.', 'Top multinational and domestic automotive companies choose our Panasonic Welding Systems to significantly improve weld quality and boost efficiency while reducing production costs. We provide consultation, training, maintenance, and reliable after-sales service to satisfy our customers'' expectations.', E'Arc Welding Robot with Power Source\nArc Welding Equipment and Filler Metals\nPower Tools and Hand Tools\nPersonal Protective Equipment (PPEs)', 'assets/HOME/MOTOR VEHICLE.jpg'),
('metal-fabrication', 1, 'Metal Fabrication and Industrial', 'Bridges, railways, refineries, shipyards, transmission lines, and other large-scale projects require steel frames and other metals to support the large infrastructures. Workers in the metal fabrication industry do welding, metal cutting, and fastening to assemble metal parts.', 'We supply our clients with equipment that makes quality welds in a short time. Our safety products protect workers from hazards such as working from heights, sparks, glaring lights, and hazardous gases.', E'Arc Welding Equipment and Filler Metals\nPlate Cutting and Beveling Equipment\nGas Welding and Cutting Equipment\nPower Tools and Hand Tools\nPersonal Protective Equipment (PPEs)', 'assets/HOME/METAL FABRICATION.jpg'),
('power-generation', 2, 'Power Generation', 'The Power Generation Industry is vital in a country''s growth. They must be a reliable partner in meeting the Philippine Energy Market''s ever-growing demands.', 'From plant maintenance, shutdown, building power transmission lines, and other infrastructures, we work closely with our clients and supply them finish their projects on schedule.', E'Arc Welding Equipment and Filler Metals\nPower Tools and Hand Tools\nGrinders, Maintenance Tools and Equipment\nBearings, Maintenance Tools and Equipment\nHeight Protection Equipment and other PPEs', 'assets/HOME/POWER GENERATION.jpg'),
('oil-petrochemical', 3, 'Oil and Petrochemical Industry', 'Oil refineries use fractional distillation and other methods to process crude oil into more useful products like petroleum, gasoline, and other fuels. During the distillation, heavier by-products settle at the bottom. Petrochemical plants crack the by-products and further process them into more useful chemicals. Other industries use these petrochemicals to create different products.', 'Oil and petrochemical industries regularly perform industrial works (projects) that require maintenance, shutdowns, and expanding facilities and pipelines. We provide our clients with safety products, equipment and consumables for maintaining the facilities and building industrial projects.', E'Arc Welding Equipment and Filler Metals\nPortable Gas Detectors\nAir Movers and Industrial Ventilators\nBearings, Maintenance Tools and Equipment\nPipe Cutting and Beveling Machine\nPower Tools and Hand Tools\nPersonal Protective Equipment (PPEs)', 'assets/HOME/OIL AND PETROCHEMICAL.jpg'),
('mining', 4, 'Mining Industry', 'This industry extracts coal, oil, metals, and other raw materials from the earth. These resources are processed by other industries to create products such as fuel, jewelry, construction materials, and everyday items. Mining is vital to the economy.', 'However, digging deep into the ground could pose a safety risk to workers without the proper equipment. We at Andison promote safety by providing high-quality PPEs. Our portfolio includes various single and multi-gas detectors including maintenance-free gas detection. We provide clients with training on the proper use of the equipment to fully use its functions and ensure a safe working environment. We also do recalibration for the gas detection.', E'Portable and Multi-Gas Detectors\nPPEs and other Safety Products\nAir Movers and Ventilation Equipment\nBearings, Maintenance Tools and Equipment\nCordless Power Tools\nFloodlights and other Light Sources', 'assets/HOME/MINING.jpg'),
('shipyard', 5, 'Shipyard', 'World trade relies heavily on freight ships because it offers a high capacity at a low cost in transporting goods. Being an archipelago, the Philippines also uses ships to ferry people to the country''s many islands. Shipyards play a critical role in maintaining ships, ensuring they are seaworthy and safe.', 'Metal fabrication is an integral part of the shipbuilding industry. Andison has a wide product catalog for working with metal fabrication, providing clients with equipment ready for the job.', E'Arc Welding Equipment and Filler Metals\nGas Welding and Cutting Equipment\nAir Movers and Industrial Ventilators\nPower Tools and Hand Tools\nPipe Cutting and Beveling Machine\nPersonal Protective Equipment (PPEs)\nPortable Gas Detectors', 'assets/HOME/shipyard.jpg')
on conflict (slug) do update set
    sort_order = excluded.sort_order,
    title = excluded.title,
    summary = excluded.summary,
    details = excluded.details,
    products_list = excluded.products_list,
    image_url = excluded.image_url;
